config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  post 'accept' => 'invites#accept'
  get 'user_groups' => 'groups#user_groups'
  get 'members' => 'groups#members'

  resources :tasks do
    resources :completions, only: :create
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index,:show]
  resources :assignments, except: [:edit, :update]
  resources :completions, except: [:edit, :update]
  resources :memberships, only: :destroy
  resources :groups, except: [:index, :update, :edit]
  resources :tasks, except: [:update, :edit]
  resources :welcome, only: :index
  resources :invites, except: [:index, :edit, :update]

  resources :conversations, only: [:create, :show] do
    resources :messages, only: :create
  end

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :group
  has_many :messages

  accepts_nested_attributes_for :messages
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  def show
    @conversation = Conversation.find(params[:id])
    @messages = @conversation.messages
    @skip_footer = true;
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/show.html.erb
<div class="row" id="chat-window">
  <div class="col s12">

    <div class="row messages-container">
      <% if @messages %>
        <% @messages.each do |message| %>
          <% if message.from current_user %>

            <div class="this-chatter" id="chatter_<%=message.sender.id%>">
              <img class="chat-img" src="<%=message.sender.image%>" alt="<%=message.sender.initials%>"/>
              <div class="chip">
                <%= message.content %>
              </div>
            </div>

          <% else %>

            <div class="other-chatter" id="chatter_<%=message.sender.id%>">
              <img class="chat-img" src="<%=message.sender.image%>" alt="<%=message.sender.initials%>"/>
              <div class="chip">
                <%= message.content %>
              </div>
            </div>

          <% end %>
        <% end %>
      <% end %>
    </div>


    <div class="input-field col s12 message-form">
      <%= form_for [@conversation, Message.new], remote: true do |f| %>
        <%= f.text_area :content, class:"materialize-textarea message-input" %>
        <%= f.label "Say something:", id:'content' %>
        <%= f.hidden_field :conversation_id, value: @conversation.id %>
        <button class="waves-effect waves-light btn chat-button red lighten-2 right">
          <%= f.submit "send" %>
        </button>
      <% end %>
    </div>

  </div>
</div>

<%= subscribe_to conversation_path(@conversation) %>