config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  post 'accept' => 'invites#accept'
  get 'user_groups' => 'groups#user_groups'
  get 'members' => 'groups#members'

  resources :tasks do
    resources :completions, only: :create
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index,:show]
  resources :assignments, except: [:edit, :update]
  resources :completions, except: [:edit, :update]
  resources :memberships, only: :destroy
  resources :groups, except: [:index, :update, :edit]
  resources :tasks, except: [:update, :edit]
  resources :welcome, only: :index
  resources :invites, except: [:index, :edit, :update]

  resources :conversations, only: [:create, :show] do
    resources :messages, only: :create
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :memberships
	has_many :users, through: :memberships
	has_many :tasks
	has_many :invites

	has_one :conversation

	validates :name, presence: true

	def activity
		activity = self.creations + self.assignments + self.invitations + self.memberships + self.completions
		activity.uniq!
		activity.sort_by{ |event| event.updated_at }.reverse
	end

	def creations
		self.tasks if self.tasks
	end

	def assignments
		assignments = []
		self.creations.each{|task| task.assignments.each{|a| assignments << a} if task.assignments}
		assignments
	end

	def completions
		completions = []
		self.creations.each{|task|task.completions.each{|c| completions << c} if task.completions}
		completions
	end

	def invitations
		self.invites if self.invites
	end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!

  def user_groups
    @groups = current_user.groups
  end
  
  def show
    @group = Group.find_by(id: params[:id])
    redirect_to_user
    @members = @group.users
    @task = Task.new
    @membership = Membership.new
    @invite = Invite.new
    @tasks_this_week = @group.tasks.where(due_date: Date.today..(Date.today + 7)).count
    @data_for_chart = [{name: "Weekly Tasks", y: @tasks_this_week} ]
    @members.each do |member|
      @data_for_chart.push({
        name: member.name, 
        y: member.tasks.select{ |task| task.completions.select {|completed_task| completed_task.completed == false}}.length
      }) 
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      @membership = Membership.create(group_id: @group.id, user_id: current_user.id)
      Conversation.create!(group_id: @group.id)
      redirect_to @group
    else
      flash[:errors] = @group.errors.full_messages
      redirect_to '/groups/new'
    end

  end

  def members
    @group = Group.find_by(id: params[:format])
    if request.xhr?
      return render partial: '/groups/members', layout: false
    end
  end

  def destroy
    @group.destroy
  end

  private
    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper

	def member?(user)
		!find_by_email(user).empty? if find_by_email(user)
	end

	def find_by_email(user)
		if @group
			@group.memberships.select do |p|
				p.user.email == user.email
			end
		end
	end

	def redirect_to_user
		redirect_to current_user unless member?(current_user)
	end

	def user(event)
		case event.class.name
		when "Task"
			event.user
		when "Assignment"
			event.assigner
		when "Invite"
			event.inviter
		when "Completion"
			event.completer
		when "Membership"
			event.user
		end
	end

	def verb(event)
		case event.class.name
		when "Task"
			"created"
		when "Assignment"
			"assigned"
		when "Invite"
			"invited"
		when "Completion"
			"completed"
		when "Membership"
			"joined the group."
		end
	end

	def direct_task(event)
		case event.class.name
			when "Task"
				event
			when "Completion"
				event.task
			when "Assignment"
				event.task
		end
	end

	def direct_user(event)
		event.invitee if event.class.name == "Invite"
	end

	def preposition(event)
		case event.class.name
		when "Assignment"
			"to"
		when "invited"
			"to the group."
		end
	end

	def indirect_user(event)
		event.assignee if event.class.name == "Assignment"
	end

end

app/views/groups/_group_members.html.erb
<div class="row" id="group-members">
	<h6 id="members"><%=@group.name%>'s members<h6>
	<ul class="collection" id="group-membership">
		<%@group.users.each do |user|%>
			<li class="collection-item avatar">
				<img src="<%=user.image%>" class="circle" style="height:3.5em;width:3.5em;"/>
				<%=user.name%>
			</li>
		<%end%>
	</ul>
</div>

app/views/groups/_members.html.erb
<div class='members'>
<% @group.users.each do |m| %>
	<div class="chip teal lighten-3">
    <img class="image member-img" src="<%=m.image%>" alt="<%=m.initials%>"/>
		<span class="member_name"><%= m.first_name %></span>
  </div>
<% end %>
</div>

app/views/groups/group_members.html.erb
<h1>Group memberships</h1>

<% @groups.each do |group|%>
<%= group.name%>
<%end%>

app/views/groups/new.html.erb
<div class="container group-form">
<% provide(:title, '| Create a Group') %>
<h4 class="create-group">Create a group:</h4>
<div>
<% if flash %>
      <% flash.each do |key, value| %>
        <div><%= value.first %></div>
      <% end %>

<% end %>
</div>

<div>
  <div>
    <%= form_for(@group) do |f| %>
      <%= f.text_field :name, placeholder: "group name"%>
      <button class="waves-effect waves-light btn">
        <%= f.submit "create" %>
      </button>

    <% end %>
  </div>
</div>
</div>

app/views/groups/show.html.erb
<div class="container">
	<div>
		<h4 class="center-align group-name"><%= @group.name %></h4>
	</div>

	<% if @group.tasks.length > 1 %>
	  <div id="container" style="width:100%; height:350px;" data-chart-info="<%= @data_for_chart.to_json %>"></div>
	<%end%>
	<%= link_to "Members", members_path(@group), class: "see-members"%>	
	<div id="group-members"></div>
	<div class="row">
		<ul class="collection">
				<% @group.activity.each do |event| %>
				<li class="collection-item avatar">
					<img src="<%=user(event).image%>" class="circle" style="height:3.5em;width:3.5em;"/>
						<%= link_to user(event).name, user_path(user(event)) if user(event) %>

						<%= verb(event) if verb(event) %>

						<%= link_to direct_task(event).task, task_path(event) if direct_task(event) %>

						<%= link_to direct_user(event).name, user_path(event) if direct_user(event) %>

						<%= preposition(event) if preposition(event) %>

						<%= link_to indirect_user(event).name, user_path(event) if indirect_user(event) %>
				</li>
				<% end %>
		</ul>
	</div>
</div>

app/views/groups/user_groups.html.erb
<% @groups.each do |group| %>
    <div class="col s12 m6">
      <div class="card blue-grey lighten-5">
        <div class="card-content blue-text">
          <i class="material-icons">supervisor_account</i>
			<%= link_to group.name, group_path(group.id), class: "group-link" %>
        </div>
      </div>
    </div>
<% end %>