config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  post 'accept' => 'invites#accept'
  get 'user_groups' => 'groups#user_groups'
  get 'members' => 'groups#members'

  resources :tasks do
    resources :completions, only: :create
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index,:show]
  resources :assignments, except: [:edit, :update]
  resources :completions, except: [:edit, :update]
  resources :memberships, only: :destroy
  resources :groups, except: [:index, :update, :edit]
  resources :tasks, except: [:update, :edit]
  resources :welcome, only: :index
  resources :invites, except: [:index, :edit, :update]

  resources :conversations, only: [:create, :show] do
    resources :messages, only: :create
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  devise :omniauthable, omniauth_providers: [:facebook]

	has_many :memberships
	has_many :groups, through: :memberships

	has_many :tasks

  has_many :invites_received, foreign_key: :invitee_id, class_name: "Invite"
  has_many :invites_given, foreign_key: :inviter_id, class_name: "Invite"

	has_many :assignments

	has_many :assignments_given, foreign_key: :assigner_id, class_name: 'Assignment'
	has_many :delegated_tasks, through: :assignments_given, source: :task

	has_many :assignments_received, foreign_key: :assignee_id, class_name: 'Assignment'
	has_many :assigned_tasks, through: :assignments_received, source: :task

	has_many :completions
	has_many :completed_tasks, through: :completions, source: :task

  has_many :messages

  has_many :messages_sent, foreign_key: :sender_id, class_name: "Message"
  has_many :messages_received, foreign_key: :receiver_id, class_name: "Message"

  validates :name, presence: true
  has_many :conversations, through: :messages

  def in_group?
    self.groups.any?
  end

  def find_incomplete_tasks
    self.tasks.select do |task|
      task.completions.length == 0
    end
  end

    def high_priority
      self.incomplete_assigned_tasks.select do |task|
        task.priority == "3"
      end
    end

    def med_priority
      self.incomplete_assigned_tasks.select do |task|
        task.priority == "2"
      end
    end

    def low_priority
      self.incomplete_assigned_tasks.select do |task|
        task.priority == "1"
      end
    end

  def incomplete_assigned_tasks
    self.assigned_tasks.select do |task|
      task.completions.length == 0
    end
  end

  def initials
    self.name.split(' ').map{|name|name[0]}.join('')
  end

  def first_name
    self.name.split(' ')[0]
  end

  def last_name
    self.name.split(' ')[-1]
  end

private

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.image = auth.info.image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.search_user(search)
      where("LOWER(email) LIKE LOWER(?)", "%#{search}%")
  end

  def list_conversations
    self.conversations
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    @user.skip_confirmation!

    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  protected

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :authenticate_user!, except: [:create]
  before_filter :configure_sign_up_params

  def new
    super
  end

  def create
    super
  end

  def edit
    super
  end

  def update
    super
  end

  def destroy
    super
  end

  def cancel
    super
  end

  # protected
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  def new
    super
  end

  def create
    super
  end

  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!
  
  def show
  	@invite = Invite.new
    @user = User.find_by(id: current_user.id)
    @groups = @user.groups
    @tasks = @user.tasks.order('created_at ASC')
    @completed_tasks = @user.completed_tasks.order('date_complete DESC')
  end


end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/show.html.erb
<% if current_user %>
  <div class="profile-pic">
    <img src="<%=current_user.image%>", class="circle"/>
  </div>
<% end %>

<% current_user.invites_received.each do |invite| %>
    <div class="col s12 m6">
      <div class="card blue-grey lighten-5">
        <div class="card-content blue-text">
                  <%= form_tag(accept_path, method: "post") do %>
                  <%= hidden_field_tag :group_id, invite.group.id %>
                  <%= submit_tag "thumb_up", class:"material-icons thumb_up" %>
                  <%= link_to invite.inviter.first_name, user_path(invite.inviter.id) %> invited you to join <%= link_to invite.group.name, group_path(invite.group.id) %>
                <% end %>
        </div>
      </div>
    </div>
<% end %>

<% current_user.find_incomplete_tasks.each do |task| %>
  <div class="col s12 m6">
    <div class="card teal lighten-3">
      <div class="card-content blue-text">
      <i class="material-icons announcement">mode_edit</i>
          <%= link_to task.task, task_path(task.id), class: "user-profile" %>
      </div>
    </div>
  </div>
<% end %>

<% current_user.high_priority.each do |task| %>
  <div class="col s12 m6">
    <div class="card red accent-1">
      <div class="card-content white-text">
      <i class="material-icons schedule">schedule</i>
          <%= link_to task.task, task_path(task.id), class: "user-profile" %>
      </div>
    </div>
  </div>
<% end %>

<% current_user.med_priority.each do |task| %>
  <div class="col s12 m6">
    <div class="card deep-orange lighten-2">
      <div class="card-content white-text">
      <i class="material-icons schedule">schedule</i>
          <%= link_to task.task, task_path(task.id), class: "user-profile" %>
      </div>
    </div>
  </div>
<% end %>

<% current_user.low_priority.each do |task| %>
  <div class="col s12 m6">
    <div class="card amber lighten-2">
      <div class="card-content white-text">
      <i class="material-icons schedule">schedule</i>
          <%= link_to task.task, task_path(task.id), class: "user-profile" %>
      </div>
    </div>
  </div>
<% end %>